Avoid `git config set` syntax
ubuntu-slim was downgraded to a version of Git that doesn't support it.
Fixes error:

    error: key does not contain a section: set

Avoids: https://github.com/actions/runner-images/issues/14014